event_reg/event_reg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reg.urls')),
    
]

event_reg/reg/urls.py
from django.urls import path
from . import views


app_name = 'reg'

urlpatterns = [
    path('', views.home, name='home'),  
    path('info/', views.info, name='info'),
    path('new_info/' ,views.new_info , name = 'new_info')
   
]

event_reg/reg/models.py
from django.db import models


# Create your models here.

class Information(models.Model):
    name = models.CharField(max_length=25)
    email = models.CharField(max_length=45)
    number = models.IntegerField()
   

    def __str__(self):
        return self.name 
       
class Details(models.Model):
    gender = models.CharField(max_length=10)
    state = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.gender, self.state}"
   
      



event_reg/reg/forms.py
from django import forms
from. models import Information

class InformationForm(forms.ModelForm):
    class meta:
        model = Information
        field = ['text']
        label={'text': ' '}


event_reg/reg/views.py
from django.shortcuts import render, redirect

from.models import Information
from.forms import InformationForm

# Create your views here.

def home(request):
    return render(request, 'reg/home.html')

def info(request, information_id):
    info = Information.objects.by(id=information_id)
    entries =info.entry_set.order_by('-date_added')
    context = {"info": info , 'entries':entries}
    return render(request, "reg/info.html" ,context)
   
""" A context is a
dictionary in which the keys are names well use in the template to access
the data, and the values are the data we need to send to the template."""

def new_info(request):
    if request.method != 'POST':
        form=InformationForm()
        #No data submitted; create a blank form.
       
    
    else:
        # POST data submitted; process data
        form = InformationForm(data= request.POST)
        if form.is_valid():
            form.save()
            return redirect('reg:info')

    context = {'form' : form}
    return render(request, 'reg/new_info.html',context )



   




event_reg/reg/templates/reg/home.html

{%extends 'reg/layout.html'%}

{%block body%}
<head> WELCOME</head>
{% endblock%}

event_reg/reg/templates/reg/info.html
{%extends 'reg/layout.html'%}
{%block body%}
<p> EVENTS {{info}}</p>
<ul>
    {% for information in info %}
        <li>{{information}}</li>
    {%empty%}
        <ul>No events Available yet. </ul>  

    {%endfor%}   
</ul>   
<a href="{% url 'reg:new_info'%}"> Add New Event</a>            
{%endblock%}


event_reg/reg/templates/reg/layout.html
<!DOCTYPE html>
<html lang="en">
    <title> REGISTRATION</title>
    <h2> <a href="{% url 'reg:info'%}"> REGISTER HERE</a></h2>
</html>

<body>
    {% block body%}
    {% endblock%}
</body>

event_reg/reg/templates/reg/new_info.html
{% extends 'reg/layout.html'%}

{%block body%}
<p>Add a new event: </p>

<form action="{% url 'reg:new_info'%}" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button name="submit"> ADD EVENT </button>


</form>





{%endblock%}
